trigger:
- main  # Adjust to your default branch

pool:
  vmImage: 'ubuntu-latest'  # Use an appropriate image

steps:
- task: Maven@4
  inputs:
    mavenPomFile: 'pom.xml'  # Path to your pom.xml
    goals: 'package'          # Build the project
    options: '-DskipTests'    # Skip tests if desired

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)/webapp/target/webapp.war'  # Adjust to your build output directory
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)'  # Name of the zip file

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)/myapp.zip'
    artifact: 'MyJavaApp'

- task: S3Upload@1
  inputs:
    awsCredentials: 'aws-service'
    regionName: 'ap-southeast-2'
    bucketName: 'sutapa-bucket143'
    sourceFolder: '$(Build.ArtifactStagingDirectory)'
    globExpressions: '**'
    filesAcl: 'bucket-owner-full-control'
        
    